apiVersion: v1
kind: Service
metadata:
  name: trading-bot-service
  labels:
    name: trading-bot
spec:
  selector:
    app: trading-bot
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
